import dotenv from 'dotenv';
import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Vehicle from '../models/Vehicle.js';

// One-time export: dump the live vehicles collection to backend/data/car_data_full.json,
// which becomes the seed source of truth now that the frontend JSON is trimmed to the
// 6-car logged-out demo. Resolves paths from this file's location (not CWD) so it runs
// the same from the repo root or from backend/.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '../../.env.local') });

const DB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/dealer_hub';
const OUT_PATH = path.join(__dirname, '../data/car_data_full.json');

// Local static-asset paths and API image URLs are both regenerated by the seed script,
// so exporting them would only bake in staleness. External URLs (e.g. an admin pasted
// a hosted image link) are real data and survive the export.
const isRegeneratedImagePath = (value) =>
  typeof value === 'string' && (value.startsWith('/inventory_data/') || value.startsWith('/api/'));

const run = async () => {
  try {
    await mongoose.connect(DB_URI);
    const vehicles = await Vehicle.find().sort({ vehicleId: 1 }).lean();

    const records = vehicles.map(({ _id, __v, createdAt, updatedAt, image, images, ...rest }) => ({
      ...rest,
      ...(image && !isRegeneratedImagePath(image) ? { image } : {}),
    }));

    fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
    fs.writeFileSync(OUT_PATH, JSON.stringify(records, null, 2));

    console.log(`Exported ${records.length} vehicles to ${path.relative(process.cwd(), OUT_PATH)}`);
    records.forEach((r) => console.log(`  ${r.vehicleId}  ${r.make} ${r.model}`));
    process.exit(0);
  } catch (error) {
    console.error('Export failed:', error.message);
    process.exit(1);
  }
};

run();
